# Generated by Django 3.0.6 on 2020-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200627_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='racelist',
            name='racedata_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
