# Generated by Django 3.0.5 on 2020-05-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_racelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.TextField()),
                ('horse_data', models.TextField()),
                ('racelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Racelist')),
            ],
        ),
    ]
