# Generated by Django 3.0.6 on 2020-06-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_racelist_racedata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racelist',
            name='racedata_updated_at',
            field=models.DateTimeField(),
        ),
    ]
