# Generated by Django 3.0.5 on 2020-05-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_racedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
