# Generated by Django 3.0.6 on 2020-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedata',
            name='lackparams',
            field=models.TextField(default='5'),
            preserve_default=False,
        ),
    ]
