# Generated by Django 3.0.6 on 2020-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200627_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learningdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_data', models.TextField()),
                ('time_result', models.TextField()),
                ('Xmean', models.FloatField()),
                ('Xstd', models.FloatField()),
                ('Ymean', models.FloatField()),
                ('Ystd', models.FloatField()),
                ('test_score', models.FloatField()),
            ],
        ),
    ]
