# Generated by Django 3.0.6 on 2020-06-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_learningdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningdata',
            name='Xmean',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningdata',
            name='Xstd',
            field=models.TextField(),
        ),
    ]
