# Generated by Django 3.0.6 on 2020-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200628_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedata',
            name='horse_code',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
