# Generated by Django 3.0.6 on 2020-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_racedata_horse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedata',
            name='horse_code',
            field=models.TextField(default='未定'),
        ),
    ]
