# Generated by Django 3.0.6 on 2020-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200628_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='racelist',
            name='race_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
