# Generated by Django 3.0.5 on 2020-05-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsusers', '0002_auto_20200530_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smsusers.PhoneNumber'),
        ),
    ]
