# Generated by Django 3.0.5 on 2020-05-30 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsusers', '0003_auto_20200530_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Parent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
