# Generated by Django 3.0.6 on 2020-05-31 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsusers', '0007_auto_20200531_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsusers.AdEmail'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
